
# $Id: Makefile.win,v 1.2 2006/03/25 20:47:41 lightdruid Exp $

CXX=cl
LINK=link
#CXXFLAGS=/nologo /c /EHsc /D_USE_MATH_DEFINES /Gz /MDd
CXXFLAGS=/nologo /c /EHsc /D_USE_MATH_DEFINES /Gz /Zi
LDFLAGS=
INCLUDES=/I. /I../include

DEST=.

SRCS = t1.cc

OBJS = $(SRCS:.cc=.obj) 
EXEC1 = t1.exe

all: $(EXEC1)

$(EXEC1): $(SRCS)
    @$(CXX) $(CXXFLAGS) $(INCLUDES) $(SRCS)
    @$(LINK) $(LDFLAGS) $(OBJS) ../lib/mozg.lib

# ---
